### ISSUE TITLE
Plugin "netlify-plugin-no-more-404" internal error

### ISSUE THREAD

**Issue by Arjun-chaurasiya** [sw-yx/netlify-plugin-no-more-404#13]
Error message:ENOENT: no such file or directory, scandir '/opt/build/repo/opt/build/repo'
Error location:In "onPostBuild" event in "netlify-plugin-no-more-404" from netlify.toml

**Comment by ehmicky** [comment]
Hi @Arjun-chaurasiya,
This is a duplicate of #4.
